# Generated by Django 3.2 on 2023-02-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='defaults/default_blog.png', upload_to='blogs/'),
        ),
    ]
