# Generated by Django 3.2 on 2023-02-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20230218_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(choices=[(1, 'Repair'), (2, 'Baby')])),
            ],
        ),
    ]
