# Generated by Django 3.2 on 2023-02-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicechoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceChoice',
        ),
    ]
