# Generated by Django 3.2 on 2023-02-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_delete_servicechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='services.subservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.customer')),
            ],
            options={
                'verbose_name': 'Service Choice',
                'verbose_name_plural': 'Service Choices',
            },
        ),
    ]
