# Generated by Django 3.2 on 2023-02-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_rename_servicechoice_servicebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBook',
        ),
    ]
