# Generated by Django 3.2 on 2023-02-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_delete_servicebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('issue', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='book_service/')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='services.subservice')),
                ('taskers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.tasker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.customer')),
            ],
            options={
                'verbose_name': 'Service Choice',
                'verbose_name_plural': 'Service Choices',
            },
        ),
    ]
