# Generated by Django 3.2 on 2023-02-18 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20230218_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.customer'),
        ),
    ]
