# Generated by Django 3.2 on 2023-02-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20230218_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order/'),
        ),
    ]
